"""Added Audition model

Revision ID: a5ae6a1bbb5f
Revises: 8c36248c4dc1
Create Date: 2023-06-10 17:51:30.358859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5ae6a1bbb5f'
down_revision = '8c36248c4dc1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
